### ISSUE TITLE
这就是在跑了？？？？

### ISSUE THREAD

**Issue by macdaox** [yuanluoyue/rbnb-mine#1]
![CleanShot 2024-01-14 at 20 01 44@2x](https://github.com/yuanluoyue/rbnb-mine/assets/51317376/c4e5d7b0-47cf-42b7-9960-473bfac84d38)

**Comment by macdaox** [comment]
看不到操作？？？？

**Comment by thexiongxx** [comment]
我也是这个、 怎么知道有没有开打哦、
