### ISSUE TITLE
启动之后立马停止了

### ISSUE THREAD

**Issue by dh12306** [yuanluoyue/rbnb-mine#3]
按文档安装，结果启动之后立马报错了@yuanluoyue
![image](https://github.com/yuanluoyue/rbnb-mine/assets/20471681/ad7ba9df-be5e-402d-857f-7db5acaa8957)

**Comment by bubblle** [comment]
我也是，你解决了吗

**Comment by yuanluoyue** [comment]
项目方的服务挂了

**Comment by MRwangsicong** [comment]
同样遇到这个问题

**Comment by neicedai** [comment]
同样问题，网页能正常挖

**Comment by cxMax** [comment]
pm2 怎么看日志噢 ，大哥， 我试了下，运行2s 差不多就断开了， 也看不到日志， 不知道报错在哪，还寻思着，自己调试下的

**Comment by itheboy** [comment]
我也是什么情况这是
